### ISSUE TITLE
pytesseract.pytesseract.TesseractNotFoundError

### ISSUE THREAD

**Issue by NoWayBg** [ChayanBansal/roi_selection_and_ocr_with_orientation_correction#1]
Hello,
I already download and try to run your file,
But  there is an error occur,
Can you check and support my error (I am new member Python).
Thank you so much.
`C:\Users\NOWAY\Downloads\roi_selection_and_ocr_with_orientation_correction-master>py roi_selection_with_orientation_and_ocr.py
Traceback (most recent call last):
  File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 184, in run_tesseract
    proc = subprocess.Popen(cmd_args, **subprocess_args())
  File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "roi_selection_with_orientation_and_ocr.py", line 116, in <module>
    text = pytesseract.image_to_string(image_roi)
  File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
    }[output_type]()
  File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 308, in <lambda>
    Output.STRING: lambda: run_and_get_output(*args),
  File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
    run_tesseract(**kwargs)
  File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 186, in run_tesseract
    raise TesseractNotFoundError()
pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your path`

**Comment by ChayanBansal** [comment]
> Hello,
> I already download and try to run your file,
> But there is an error occur,
> Can you check and support my error (I am new member Python).
> Thank you so much.
> `C:\Users\NOWAY\Downloads\roi_selection_and_ocr_with_orientation_correction-master>py roi_selection_with_orientation_and_ocr.py
> Traceback (most recent call last):
> File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 184, in run_tesseract
> proc = subprocess.Popen(cmd_args, **subprocess_args())
> File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 729, in **init**
> restore_signals, start_new_session)
> File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 1017, in _execute_child
> startupinfo)
> FileNotFoundError: [WinError 2] The system cannot find the file specified
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "roi_selection_with_orientation_and_ocr.py", line 116, in
> text = pytesseract.image_to_string(image_roi)
> File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 309, in image_to_string
> }output_type
> File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 308, in
> Output.STRING: lambda: run_and_get_output(*args),
> File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 218, in run_and_get_output
> run_tesseract(**kwargs)
> File "C:\Users\NOWAY\AppData\Local\Programs\Python\Python36\lib\site-packages\pytesseract\pytesseract.py", line 186, in run_tesseract
> raise TesseractNotFoundError()
> pytesseract.pytesseract.TesseractNotFoundError: tesseract is not installed or it's not in your path`

Hey @NoWayBg !
Thanks for asking this question.
It seems that you might have not installed the tesseract engine. Please download it from https://github.com/tesseract-ocr/tesseract/wiki#windows and set the PATH variable properly.

I hope it resolves your issue.
Regards
Chayan
